[package]
name = "adagram"
version = "0.1.0"
edition = "2018"

[profile.release]
debug = true

[dependencies]
corp = { path = "../corp" }
spfunc = "0.1.0"
ndarray = "0.15.4"
ndarray-rand = "0.14.0"
clap = { version = "3.0.7", features = ["derive"] }
binary-heap-plus = "0.4.1"
